version: '3'

services:
  reverse-proxy:
    container_name: lemp_traefik
    restart: unless-stopped
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    environment:
      - "CF_DNS_API_TOKEN={CF_TOKEN}"
      - "CF_ZONE_API_TOKEN={CF_TOKEN}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
      - ./traefik.yml:/traefik.yml:ro
      - ./.htpasswd:/.htpasswd
    networks:
      - web
    command:
      - --certificatesresolvers.cloudflare.acme.tlschallenge=true
      - --certificatesresolvers.cloudflare.acme.email={CERT_EMAIL}
      # Disable for production
      - --certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.{DOMAIN}`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/.htpasswd"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.{DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.middlewares=auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main={DOMAIN}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.{DOMAIN}"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.docker.network=traefik_default"
     
      
  mariadb:
    image: mariadb
    restart: unless-stopped
    container_name: lemp_mariadb
    volumes:
      - ./mariadb/conf/:/etc/mysql/
      - ./mariadb/lib/:/var/lib/mysql
      - ./mariadb/log/:/var/log/mariadb/
      - ./mysql/log/:/var/log/mysql/
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: {MYSQL_R_PASSWORD}
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: {MYSQL_MAUTIC_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lemp_pma
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - web
      - backend
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`pma.{DOMAIN}`)"
      - "traefik.http.routers.pma.entrypoints=http"
      - "traefik.http.routers.pma.middlewares=traefik-https-redirect"
      - "traefik.http.routers.pma-secure.rule=Host(`pma.{DOMAIN}`)"
      - "traefik.http.routers.pma-secure.middlewares=auth"
      - "traefik.http.routers.pma-secure.entrypoints=https"
      - "traefik.http.routers.pma-secure.tls.certresolver=cloudflare"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_default"

  mautic:
    restart: unless-stopped
    image: mautic/mautic
    container_name: lemp_mautic
    depends_on:
      - mariadb
    environment:
      MAUTIC_DB_HOST: mariadb
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: {MYSQL_MAUTIC_PASSWORD}
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
    volumes:
      - ./mautic/web:/var/www/html
    networks:
      - backend
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mautic.rule=Host(`mautic.{DOMAIN}`)"
      - "traefik.http.routers.mautic.entrypoints=http"
      - "traefik.http.routers.mautic.middlewares=traefik-https-redirect"
      - "traefik.http.routers.mautic-secure.rule=Host(`mautic.{DOMAIN}`)"
      - "traefik.http.routers.mautic-secure.middlewares=auth"
      - "traefik.http.routers.mautic-secure.entrypoints=https"
      - "traefik.http.routers.mautic-secure.tls.certresolver=cloudflare"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_default"

  apache2:
    container_name: lemp_apache2
    build: './'
    restart: always
    volumes:
      - ./public/:/var/www/html/
      - ./apache2/:/etc/apache2/
    networks:
      - web
      - backend
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache2.rule=Host(`{DOMAIN}`)"
      - "traefik.http.routers.apache2.entrypoints=http"
      - "traefik.http.routers.apache2.middlewares=traefik-https-redirect"
      - "traefik.http.routers.apache2-secure.rule=Host(`{DOMAIN}`)"
      - "traefik.http.routers.apache2-secure.entrypoints=https"
      - "traefik.http.routers.apache2-secure.tls.certresolver=cloudflare"
      - "traefik.docker.network=traefik_default"

networks:
  web:
    external:
      name: traefik_default
  backend:
    external: false

